Vagrant.configure("2") do |config|
  config.vm.box = "hallsholicker/centos8-stream-k8s"

  config.vm.define "k8s-controller-1" do |controller1|
    controller1.vm.network "private_network", ip: "10.240.0.11"
  end

  config.vm.define "k8s-controller-2" do |controller2|
    controller2.vm.network "private_network", ip: "10.240.0.12"
  end

  config.vm.define "k8s-controller-3" do |controller3|
    controller3.vm.network "private_network", ip: "10.240.0.13"
  end

  config.vm.define "k8s-worker-1" do |worker1|
    worker1.vm.network "private_network", ip: "10.240.0.21"
  end

  config.vm.define "k8s-worker-2" do |worker2|
    worker2.vm.network "private_network", ip: "10.240.0.22"
  end

  config.vm.define "k8s-worker-3" do |worker3|
    worker3.vm.network "private_network", ip: "10.240.0.23"
  end
  
  config.vm.define "k8s-client" do |client|
    client.vm.network "private_network", ip: "10.240.0.100"
  end
end
