Vagrant.configure("2") do |config|
  config.vm.box = "hallsholicker/centos8-stream-k8s"

  config.vm.define "k8s-master-1" do |master1|
    master1.vm.network "private_network", ip: "10.240.0.11"
  end

  config.vm.define "k8s-master-2" do |master2|
    master2.vm.network "private_network", ip: "10.240.0.12"
  end

  config.vm.define "k8s-master-3" do |master3|
    master3.vm.network "private_network", ip: "10.240.0.13"
  end

  config.vm.define "k8s-worker-1" do |worker1|
    worker1.vm.network "private_network", ip: "10.240.0.21"
  end

  config.vm.define "k8s-worker-2" do |worker2|
    worker2.vm.network "private_network", ip: "10.240.0.22"
  end

  config.vm.define "k8s-worker-3" do |worker3|
    worker3.vm.network "private_network", ip: "10.240.0.23"
  end
  
  config.vm.define "k8s-client" do |client|
    client.vm.network "private_network", ip: "10.240.0.100"
  end
end
