- name: Make k8s directory
  connection: local
  file:
    path: "~/k8s"
    state: directory
  when:
    - "'Client' in group_names "

- name: Download cfssl & cfssljosn
  connection: local
  get_url:
    url: "{{ item }}"
    dest: "~/k8s"
    mode: 0775
  with_items:
    - "https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/{{ v_cfssl_version }}/linux/cfssl"
    - "https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/{{ v_cfssl_version }}/linux/cfssljson"
  when:
    - "'Client' in group_names "

- name: Move cfssl & cfssljson
  connection: local
  copy:
    src: "{{ v_user_home }}/k8s/{{ item }}"
    dest: /usr/local/bin
  become: true
  with_items:
    - "cfssl"
    - "cfssljson"
  when:
    - "'Client' in group_names "

- name: Download kubectl
  connection: local
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ v_kubernetes_version }}/bin/linux/amd64/kubectl"
    dest: "~/k8s"
    mode: 0775
  when:
    - "'Client' in group_names "

- name: Move kubectl
  connection: local
  command: "mv /home/vagrant/k8s/kubectl /usr/local/bin"
  become: true
  when:
    - "'Client' in group_names "
