- name: Read id_rsa.pub
  connection: local
  command: "cat ~/.ssh/id_rsa.pub"
  register: id_rsa_pub
  when:
    - "'Client' in group_names"

- name: Add remote authorized_keys
  lineinfile:
    dest: ~/.ssh/authorized_keys
    line: " {{id_rsa_pub.stdout}}"
