- hosts: all
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - name: Local add /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: "{{ item.ip }} {{ item.hostname }}"
    with_items:
      - { ip: '10.240.0.10', hostname: 'k8s-controller' }
      - { ip: '10.240.0.11', hostname: 'k8s-controller-1' }
      - { ip: '10.240.0.12', hostname: 'k8s-controller-2' }
      - { ip: '10.240.0.13', hostname: 'k8s-controller-3' }
      - { ip: '10.240.0.21', hostname: 'k8s-worker-1' }
      - { ip: '10.240.0.22', hostname: 'k8s-worker-2' }
      - { ip: '10.240.0.23', hostname: 'k8s-worker-3' }
      - { ip: '10.240.0.100', hostname: 'k8s-client' }
    become: true
    run_once: true

  - name: Remote SSH key scan
    command: /usr/bin/ssh-keyscan -t rsa {{ hostname }}
    register: remote_ssh_key

  - name: Add ansible_host to known_hosts
    known_hosts:
      name: "{{ hostname }}"
      key: "{{ item }}"
    with_items:
      - "{{ remote_ssh_key.stdout_lines }}"

  - name: Remote SSH key scan
    command: /usr/bin/ssh-keyscan -t rsa {{ ansible_host }}
    register: remote_ssh_key

  - name: Add ansible_host to known_hosts
    known_hosts:
      name: "{{ ansible_host }}"
      key: "{{ item }}"
    with_items:
      - "{{ remote_ssh_key.stdout_lines }}"

